### PR TITLE
Test both tinygo and standard go

### PR DESCRIPTION
**Pull request by egonelbre**
This adds tests for both std go and tinygo.

It also does some project cleanup:
* remove the `.wasm` files, because it looks like it's not necessary to commit them
* remove `.work` file and example submodule, because they cause more problems than they solve (in this case)
* move the examples to separate folders, because that allows different IDE-s and tooling to work with them nicely

### CODE REVIEW

**Comment by bhelx** [comment]
You can pull my changes on `.github/workflows/ci.yml` to get the CI to go green.

**Comment by egonelbre** [comment]
@bhelx note I've rebased the code.

**Comment by nilslice** [comment]
Thank you!

I'm generally in favor of keeping .wasm in the repo (we always find a reason to download and use these modules) -- but not a requirement. 

Would like to know what @bhelx / @zshipko prefer there before going one way or the other on committing the modules.

**Comment by egonelbre** [comment]
@nilslice If they need to be downloaded one option would be to make them part of a release. (Rather than part of the source code)

**Comment by nilslice** [comment]
Yea that's preferable -- especially since Go will pull down all of this into the system cache including the wasm.

**Comment by zshipko** [comment]
Having the wasm modules in the repo is convenient, but can be pretty annoying to work with in git. Moving them to a release instead is a good idea!

**Comment by egonelbre** [comment]
Do you want me to add the release thing in this PR or in a separate one?

**Review by bhelx — APPROVED** [review]

**Comment by bhelx** [comment]
@egonelbre this looks good to me! Let's do follow ups in other PRs

**Pull request merged**
